# Use una imagen base de Node.js. 
FROM node:16

# Define el directorio de trabajo.
WORKDIR /usr/src

# Copia el archivo 'package.json' y 'package-lock.json' (si está disponible)
# al directorio de trabajo del contenedor.
COPY package*.json ./

# Instala las dependencias de tu proyecto.
RUN yarn install

# Copia el resto de tu código fuente al contenedor.
COPY . .

# Expone el puerto que tu aplicación utilizará.
EXPOSE 3000

# Ejecuta tu aplicación.
CMD [ "node", "dist/index.js" ]
